# This workflow will build a .NET project and upload the .exe file as an artifact

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MyBO3injector
        path: |
          MyBO3injector/bin/Release/net6.0-windows/*.exe
          
